# Site settings
title: Alyssa Ayala
email: alyssaayala1203@gmail.com
url: https://alyssamayala.com
description: "Alyssa Ayala is a student, game developer, and actress. She develops in Ren'Py and Python."
keywords: "Alyssa Ayala, Alyssa M Ayala"
skills: "Student - Game Developer - Actress"
meta_author: Ayala Alyssa

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 17b1d8 #80B3FF
  primary-rgb: "24, 188, 156" #"128,179,255"
  secondary: 16348b #FD6E8A
  secondary-dark: 07153c #A2122F

# Footer settings
footer:
  copyright: Alyssa Ayala
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/alyssa-ayala-a1162b383/
  - title: github
    url: https://github.com/alyssaayala
  - title: imdb
    url: https://www.imdb.com/name/nm7582214/?ref_=ext_shr_lnk

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
